apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "192.168.1.251:6443"
clusterName: "k8s-etcd-cluster-ha"
etcd:
  external:
    endpoints:
        - https://192.168.1.245:2379
        - https://192.168.1.247:2379
        - https://192.168.1.248:2379
    
    caFile: /etc/kubernetes/pki/etcd/ca.pem
    certFile: /etc/kubernetes/pki/etcd/etcd.pem
    keyFile: /etc/kubernetes/pki/etcd/etcd-key.pem
networking:
  podSubnet: 10.244.0.0/24
apiServer:
  certSANs:
    - "192.168.1.251"